//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEDK_Dashboard.GetParker {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Output", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Output : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VEDK_Dashboard.GetParker.Park[] ParkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VEDK_Dashboard.GetParker.Park[] Parker {
            get {
                return this.ParkerField;
            }
            set {
                if ((object.ReferenceEquals(this.ParkerField, value) != true)) {
                    this.ParkerField = value;
                    this.RaisePropertyChanged("Parker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Park", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Park : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParkGSRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDEILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetselskabField;
        
        private decimal KWEffektField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ParkGSRN {
            get {
                return this.ParkGSRNField;
            }
            set {
                if ((object.ReferenceEquals(this.ParkGSRNField, value) != true)) {
                    this.ParkGSRNField = value;
                    this.RaisePropertyChanged("ParkGSRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EDEIL {
            get {
                return this.EDEILField;
            }
            set {
                if ((object.ReferenceEquals(this.EDEILField, value) != true)) {
                    this.EDEILField = value;
                    this.RaisePropertyChanged("EDEIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Netselskab {
            get {
                return this.NetselskabField;
            }
            set {
                if ((object.ReferenceEquals(this.NetselskabField, value) != true)) {
                    this.NetselskabField = value;
                    this.RaisePropertyChanged("Netselskab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal KWEffekt {
            get {
                return this.KWEffektField;
            }
            set {
                if ((this.KWEffektField.Equals(value) != true)) {
                    this.KWEffektField = value;
                    this.RaisePropertyChanged("KWEffekt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetParker.GetParkerSoap")]
    public interface GetParkerSoap {
        
        // CODEGEN: Generating message contract since element name GetParkerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParker", ReplyAction="*")]
        VEDK_Dashboard.GetParker.GetParkerResponse GetParker(VEDK_Dashboard.GetParker.GetParkerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParkerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParker", Namespace="http://tempuri.org/", Order=0)]
        public VEDK_Dashboard.GetParker.GetParkerRequestBody Body;
        
        public GetParkerRequest() {
        }
        
        public GetParkerRequest(VEDK_Dashboard.GetParker.GetParkerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParkerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime inputDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid SupplierGUID;
        
        public GetParkerRequestBody() {
        }
        
        public GetParkerRequestBody(System.DateTime inputDate, System.Guid SupplierGUID) {
            this.inputDate = inputDate;
            this.SupplierGUID = SupplierGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParkerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParkerResponse", Namespace="http://tempuri.org/", Order=0)]
        public VEDK_Dashboard.GetParker.GetParkerResponseBody Body;
        
        public GetParkerResponse() {
        }
        
        public GetParkerResponse(VEDK_Dashboard.GetParker.GetParkerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParkerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VEDK_Dashboard.GetParker.Output GetParkerResult;
        
        public GetParkerResponseBody() {
        }
        
        public GetParkerResponseBody(VEDK_Dashboard.GetParker.Output GetParkerResult) {
            this.GetParkerResult = GetParkerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetParkerSoapChannel : VEDK_Dashboard.GetParker.GetParkerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetParkerSoapClient : System.ServiceModel.ClientBase<VEDK_Dashboard.GetParker.GetParkerSoap>, VEDK_Dashboard.GetParker.GetParkerSoap {
        
        public GetParkerSoapClient() {
        }
        
        public GetParkerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetParkerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetParkerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetParkerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VEDK_Dashboard.GetParker.GetParkerResponse VEDK_Dashboard.GetParker.GetParkerSoap.GetParker(VEDK_Dashboard.GetParker.GetParkerRequest request) {
            return base.Channel.GetParker(request);
        }
        
        public VEDK_Dashboard.GetParker.Output GetParker(System.DateTime inputDate, System.Guid SupplierGUID) {
            VEDK_Dashboard.GetParker.GetParkerRequest inValue = new VEDK_Dashboard.GetParker.GetParkerRequest();
            inValue.Body = new VEDK_Dashboard.GetParker.GetParkerRequestBody();
            inValue.Body.inputDate = inputDate;
            inValue.Body.SupplierGUID = SupplierGUID;
            VEDK_Dashboard.GetParker.GetParkerResponse retVal = ((VEDK_Dashboard.GetParker.GetParkerSoap)(this)).GetParker(inValue);
            return retVal.Body.GetParkerResult;
        }
    }
}
